### ISSUE TITLE
Duration

### ISSUE THREAD

**Issue by wolkenmachine** [nonlinear-thinkering-group/hdsa2018-dat-py-ws#1]
I guess this is enough for 1/2 - 1 day workshop? It's still mainly technical, do we need to expand on design/artistic aspects?

**Comment by sonn-gamm** [comment]
i think we need to write an actual text, based on the question they ask [here](https://docs.google.com/forms/d/e/1FAIpQLSeAmv9ae0AJV8kkXtSFFohQ_Dy7HsDa0h4LwbPaeqSLPUG3SA/viewform):

- What's your current occupation?
- What's the workshop about? (Explain the theme or main topic of your workshop)
- Tell us your motivation to organise this workshop (In short, write why you think this workshop would be relevant for this year's edition of H&D Summer Academy)
- What do you think other participants will learn?
- Do you expect a certain outcome? (What do you want to get out of this workshop and how would it contribute to the Hackers & Designers Community)
- What are the requirements for your workshop? (Technical conditions, required materials, equipment or technical support)

I'm gonna do it now!

**Comment by sonn-gamm** [comment]
see 22a94a1493eb496a5214669ccef6a5b309ae669c

split up into different files, the `readme` a bit dull now. let's focus on the `proposal` file.
